[package]
name = "sequoiarecover-gui"
version = "0.1.0"
edition = "2021"

[dependencies]
sequoiarecover = { package = "sequoiarecover-core", path = "../core" }
eframe = "0.31"
chrono = { version = "0.4", features = ["serde"] }
serde_json = "1.0"
