[package]
name = "management-server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
jsonwebtoken = "8"
totp-lite = "2.0"
rand = "0.8"
chrono = { version = "0.4", features = ["serde"] }

